### ISSUE TITLE
Ineffective methodology

### ISSUE THREAD

**Issue by overwriting** [eballai/NoAI#1]
Sorry to say, but this will not work as you intend. The generative art models begin with noise and apply different pixels, so they will not recreate your watermark. The[ Invisible Watermark](https://github.com/ShieldMnt/invisible-watermark) project you used to make this NoAI watermark project is indeed great, but they say in the readme: 

> "The algorithm cannot guarantee to decode the original watermarks 100% accurately even though we don't apply any attack.
> Known defects: Test shows all algorithms do not perform well for web page screenshots or posters with homogenous background color". 
> 

Unfortunately the way invisible watermarks work at the pixel level and the process generative art models are taught with will make it ineffective.  Your initiative is awesome though, and I truly hope something similar will catch on and proliferate through the art community.

**Comment by overwriting** [comment]
It could be useful to upload your code/implementation of invisible watermark so the open source community could perhaps find a way to utilize it to protect art!!

**Comment by eballai** [comment]
we did not use that watermark library that you linked.

**Comment by overwriting** [comment]
It is in the requirements, in the zip file you link... as is opencv..

**Comment by eballai** [comment]
I'm going to check, but as far as I know it was different than the one you showed

**Comment by overwriting** [comment]
https://github.com/ShieldMnt/invisible-watermark/releases/tag/0.1.5
<img width="350" alt="Screenshot 2023-01-10 at 5 13 36 PM" src="https://user-images.githubusercontent.com/122410521/211681860-aee72964-8cde-4ec7-9954-c64afdda71f9.png">

**Comment by eballai** [comment]
ah i see what you mean. we are also working on some other tools in parallel with this one. There is another watermark app in progress by someone else. Our community is strong, and will find a way to solve this issue against bots :)
