### ISSUE TITLE
The exe published is unclear as to how it was compiled

### ISSUE THREAD

**Issue by AUSBird** [eballai/NoAI#3]
Thanks @eballai for pushing the code to the repository :)
However could we please also have how the exe was compiled published as a change to the readme or as a script in the repository?

I ask for this because the code you pushed up has a bat file to run the python script, and no clear way for how this 300MB executable file was compiled. I am not wanting to draw conclusions if I don't actually know but this exe has me a bit concerned considering it's size in comparison to the size of the code and the responses in issue #1 saying it's not using the tool some of us thought it was using.

I did ask in #2 but that issue was closed by the reporter and so opened my own issue to track this question I have.

**Comment by 4lch4** [comment]
Is the concern for any iterations of that `exe` floating around and not knowing what it does?

Because as far as I can tell the `exe` isn't mentioned anywhere in the repo now.

**Comment by StardustSauce** [comment]
My attempts to compile this with the [invisible-watermark](https://github.com/ShieldMnt/invisible-watermark) library and OpenCV using PyInstaller produced a file that's about 100 megabytes short of the provided one. I'm still not completely clear on what libraries or options for those libraries we're actually meant to use. Could you clarify the exact libraries and versions used, in addition to how they were compiled?

**Comment by AUSBird** [comment]
Yeah, we really need everything regarding this exe to be explained.

**Comment by eballai** [comment]
Hi @AUSBird  Sorry for coming back to you so late. The exe was made with a software called pyinstaller. When you install it you can find many options there for building exe files. 
About the size: This is a standalone executable file, which means if you want to run this application you don’t need to install anything at all on your machine. Not even python is required. If you run this application on a computer, where there is nothing installed, it works. That’s why it's around 300 MB because it contains all the packages and python interpreter to execute the code. 

However, there is another method to make the watermarking process, if the exe is still causing concerns. We just updated the instructions on how to do it, it will require installing python and running the script from the terminal.

**Comment by AUSBird** [comment]
Ok, could you provide the options you used please? And document it a bit better? If you can throw things into the readme and stuff that would be amazing since being able to reproduce this would make it feel less like a suspicious piece of malware.

but thanks for the clarity

**Comment by AUSBird** [comment]
Also that said my apologies if I come off as attacking, aggressive or demanding or anything like that in these issues. Was put on edge with this when someone showed it to me and wanted to get to the bottom of how safe it was.

**Comment by pitaden** [comment]
So far as I can tell: a venv wasn't used for the project, so a bunch of unrelated libraries that happened to be installed got thrown inside, even though they weren't used by the program.

Looks like the code is on the github now, though!

**Comment by KyodaiKen** [comment]
Hi [eballai](https://github.com/eballai),

to me it just seems like that the publication of this was a bit rushed.

Here's a general guideline on how to make it right and as trustworthy as possible:

- Make the sources public from the start
- Use automatism to create a standalone executable
- Make the automatism scripts available in the source so everyone knows how you create the executable

Anyway thanks for having made the sources public, so if someone doubts the legitimacy of the executable, they're able to run the script normally or make their own one. That already helps a lot.

Next time please consider the three points above so nobody is questioning your intentions.

Sorry if I came over as impolite.

Regards,
Kyo

**Comment by eballai** [comment]
Hi @KyodaiKen, Thanks! The initial plan was to release only the python script, but I thought, a regular people would find it difficult to run it through terminal, so an app would be easier to use. This was a mistake from my end. But we hope that with the updated instructions people will be able to make the process the way they want, without feeling trapped. We are also thinking to move the conversation to Discord, where we can share ideas or suggestions, if there's interest about it.

**Comment by KyodaiKen** [comment]
I totally understand that. Thank you!
