### ISSUE TITLE
virus detected by virustotal

### ISSUE THREAD

**Issue by ghost** [eballai/NoAI#4]
Ransom Win64 Wacatac.oa!s1 and Trojan Blocker.Win32.149019

**Comment by eballai** [comment]
Developers said it's just Windows flagging it like that because it comes from unknown source, but we can take down the exe  and leave only the python script online.

**Comment by eballai** [comment]
Windows 10 or other versions of windows have a lot of security, if you try to download any external exe file it is automatically blocked by windows, especially if it's a custom app.

I can take it down, and run more tests on it

**Comment by eballai** [comment]
We fixed the error. It's going to take several hours until the analysis will be updated accordingly on VirusTotal.

**Comment by ghost** [comment]
thanks
